# Generated by Django 4.1 on 2022-09-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='user_id',
            new_name='user',
        ),
    ]
